TangideApp.defaultDoc = {
	"version": 2,
	"magic": "cantk",
	"meta": {
		"general": {
			"appid": "com.tangide.demo",
			"appversion": "1.0.0",
			"appname": "Demo",
			"appdesc": "Demo",
			"gapversion": "1.0",
			"screenscale": "fix-width",
			"orientation": "portrait",
			"developer": "Unkown <unkown@tangide.com>",
			"appIcon": "/drawapp8/images/appicons/96.png",
			"screenShot1": "",
			"screenShot2": "",
			"screenShot3": ""
		},
		"extlibs": [],
		"docChangedTime": 1453503238166,
		"docSavedTime": 1453503265953
	},
	"wm": {
		"type": "ui-window-manager",
		"name": "window-manager",
		"uid": 16616,
		"z": 0,
		"w": 480,
		"h": 800,
		"pivotX": 0.5,
		"pivotY": 0.5,
		"rotation": 0,
		"opacity": 1,
		"hMargin": 0,
		"vMargin": 0,
		"scaleX": 1,
		"scaleY": 1,
		"runtimeVisible": true,
		"enable": true,
		"visible": true,
		"text": "",
		"x": 0,
		"y": 0,
		"style": {
			"lineWidth": 2,
			"lineColor": "Green",
			"fillColor": "#2F3234",
			"textColor": "Black",
			"fontSize": 24,
			"fontFamily": "serif"
		},
		"soundEffectsEnalbe": true,
		"soundMusicAutoPlay": true,
		"current": 0,
		"xAttr": 0,
		"yAttr": 0,
		"widthAttr": 2,
		"heightAttr": 0,
		"xParam": 1,
		"yParam": 1,
		"widthParam": 1,
		"heightParam": 1,
		"images": {
			"display": 2,
			"force-landscape-tips": "cantk-game/assets/images/force_landscape.png",
			"force-portrait-tips": "cantk-game/assets/images/force_portrait.png"
		},
		"events": {
			"onClick": null,
			"onChanged": null
		},
		"settings": {},
		"children": [
			{
				"type": "ui-window",
				"name": "win",
				"uid": 16617,
				"z": 2,
				"w": 480,
				"h": 800,
				"pivotX": 0.5,
				"pivotY": 0.5,
				"rotation": 0,
				"opacity": 1,
				"hMargin": 0,
				"vMargin": 0,
				"scaleX": 1,
				"scaleY": 1,
				"runtimeVisible": true,
				"enable": true,
				"visible": true,
				"text": "",
				"x": 0,
				"y": 0,
				"style": {
					"lineWidth": 2,
					"lineColor": "#C8C8C8",
					"fillColor": "#2F3234",
					"textColor": "Blue",
					"fontSize": 15,
					"fontFamily": "sans"
				},
				"animHint": "none",
				"xAttr": 0,
				"yAttr": 0,
				"widthAttr": 2,
				"heightAttr": 2,
				"xParam": 1,
				"yParam": 1,
				"widthParam": 1,
				"heightParam": 1,
				"images": {
					"display": 3
				},
				"events": {
					"onClick": null,
					"onSystemInit": null,
					"onLoad": null,
					"onOpen": null,
					"onBeforeOpen": null,
					"onClose": null,
					"onSwitchToBack": null,
					"onSwitchToFront": null,
					"onGesture": null,
					"onKeyDown": null,
					"onKeyUp": null,
					"onSwipeLeft": null,
					"onSwipeRight": null,
					"onSwipeUp": null,
					"onSwipeDown": null,
					"onPointerDown": null,
					"onPointerMove": null,
					"onPointerUp": null,
					"onDoubleClick": null,
					"onMultiTouch": null,
					"onUnload": null
				},
				"settings": {},
				"propertySheetDesc": {},
				"children": []
			}
		]
	},
	"deviceConfig": {
		"name": "general",
		"platform": "android",
		"lcdDensity": "hdpi"
	},
	"docid": 1453502963457
};

